#!/bin/bash

conf_folder=~/conf
ycsb_clients_file=${conf_folder}/ycsb-clients
master_file=${conf_folder}/master
regionservers=~/inst/conf/regionservers

export clients=$(<${ycsb_clients_file})
export master=$(<${master_file})

export hbase_rs=$(<${regionservers})

export HBASE_VER=hbase-0.98.15-SNAPSHOT
export HBASE_TAR=${HBASE_VER}-bin.tar.gz

export ycsb_dir="~/inst/ycsb"

if [ "$#" -lt 1 ] 
then
	echo "Usage: `basename $0` tso|ycsb|hbase" 1>&2
	exit 1
fi
export target=$1

case ${target} in
ycsb)
for client in $clients
do
	echo ${client}":"
	scp ~/inst/ycsb-*tar.gz aran@${client}:~/inst
	scp ~/inst/*workload* aran@${client}:~/inst
	ssh -T ${client} << EOF
		cd ~/inst
		tar xzvf ycsb-*.tar.gz
		rm -R ycsb
		mv ycsb-0.1.4 ycsb
		cp hbase-site.xml ycsb
EOF
done
;;
tso)
scp ~/inst/tso-server-bin.tar.gz aran@tso:~/inst
ssh -T tso << EOF
	cd ~/inst
	tar xvzf tso-server-bin.tar.gz
	cp ~/inst/hbase-site.xml tso-server/conf/
EOF
;;
hbase)
for server in $hbase_rs
do
	echo ${server}":"
	if [ ${server} != ${master} ]
	then
		scp ~/inst/${HBASE_TAR} aran@${server}:~/inst
		scp ~/inst/conf/* aran@${server}:~/inst/conf/
	fi
	ssh -T ${server} << EOF
		cd ~/inst
		rm -R hbase
		tar xzvf ${HBASE_TAR}
		mv ${HBASE_VER} hbase
		cp conf/* hbase/conf/
EOF
done
;;
all)
deploy hbase
deploy tso
deploy ycsb
;;
esac
