#!/bin/bash

export jps_bin=`which jps`
export conf_dir=~/conf
export clients=$(<${conf_dir}/ycsb-clients)

for client in ${clients}
do
	echo ${client}
	ssh -T ${client} <<'EOF'
		processes=`jps | grep Client | cut -d ' ' -f 1`
		if [[ "$processes" != "" ]]; then
			kill `jps | grep Client | cut -d ' ' -f 1`
		fi
EOF

done
