#!/bin/bash

export script_base="${HOME}/git/amos-master-scripts"
export bdir=$pdir   # The base directory
export TABLE="usertable"
export CF="fam"
export THREADS=150
export label=$1
shift
export workload=$1
shift
export single_thread_speed=$1
shift
export max_capacity=$1
shift
export approx_time=360

export ycsb_cmd="${bdir}/inst/ycsb/bin/ycsb run hbase"
export ycsb_load_cmd="${bdir}/inst/ycsb/bin/ycsb load hbase"
export ycsb_common_params="-cp ${bdir}/inst/conf -P ${bdir}/inst/${workload} -p table=${TABLE} -p columnfamily=${CF} -p histogram.buckets=10"
export ycsb_run_params="-s"
export ycsb_load_params="-threads 100 -s " #-p autoFlush=false"

export ops_param=" -p operationcount="
#export single_thread_speed=200	
#export max_capacity=8000
export splits=0

export load_batch_size=100
export timeout=200

#checkout what interface to use on tso
export iface=$(ssh tso ifconfig | grep -B1 `grep tso /etc/hosts | cut -f 1` | head -n1 | cut -d' ' -f 1) 
export tso_cmd="${bdir}/inst/tso-server/bin/omid.sh tso -metricsConfigs console:_:10:SECONDS -networkIface ${iface} -batchPersistTimeout ${timeout}"
export tso_batchsize="-maxBatchSize "

threads=$@ #(1 2 5 10 20 50 100 120 150)
#threads=(1 2)

${script_base}/clean_hbase.sh

for thread in ${threads[@]}; do
        rate=$(echo "rate=${thread}*${single_thread_speed}; if (rate>${max_capacity}) ${max_capacity} else rate" | bc -l)
        ops=$(echo "${rate}*${approx_time}" | bc -l)

        echo "********************************************************************************"
	date
        echo "Approx Rate = "${rate}" ops/sec, Threads="${thread}
        echo "********************************************************************************"

        #kill TSO and clients (in case there are any left over
        ${script_base}/kill_clients
        ${script_base}/kill_tso
	
	#clean hbase and start anew
	stop-hbase.sh
	sleep 5
	start-hbase.sh
	sleep 3
	${script_base}/fresh_hbase_start.sh ${splits}


	#load the database
	echo ${ycsb_load_cmd} ${ycsb_common_params} ${ycsb_load_params}
	ssh -T ycsb << EOF
		${ycsb_load_cmd} ${ycsb_common_params} ${ycsb_load_params}
EOF

        #flush everything to make sure there are files on the disk
        #echo 'Flushing everything'
        #hbase shell << EOF
        #        flush 'OMID_COMMIT_TABLE'
        #        flush 'OMID_TIMESTAMP'
        #        flush 'usertable'
#EOF
	
	hbase org.jruby.Main ~/git/amos-master-scripts/RegionsStats.rb
	#start the test
	echo ${ycsb_cmd} ${ycsb_common_params} ${ycsb_run_params} ${ops_param}${ops} -threads ${thread} 
	ssh -T ycsb << EOF &> ${pdir}/out/${label}-threads${thread}.txt &
		${ycsb_cmd} ${ycsb_common_params} ${ycsb_run_params} ${ops_param}${ops} -threads ${thread}
EOF
	wait $!
	hbase org.jruby.Main ~/git/amos-master-scripts/RegionsStats.rb

done;
mail_cmd="echo `basename $0` \"finished with parameters = ${threads}\" | mail -s \"Test ${label}\" aran.bergman@gmail.com"
ssh users.emulab.net $mail_cmd
