#!/bin/bash

threads="20 1 3 5 10 15 25 30 40 60 80 100 120"

suffix="1Ru2Rc10G-noReadTSO-noflush"

label=amosMixUpdate_${suffix}
#nohup run_amos_threads $label Sworkload-um 200 3300 ${threads} &>> $pdir/out/${label}.log & 
nohup run_amos_threads $label Sworkload-um 200 5100 ${threads} &>> $pdir/out/${label}.log & 
wait $!

label=amosMixRead_${suffix}
#nohup run_amos_threads $label Sworkload-rm 320 12000 ${threads} &>> $pdir/out/${label}.log & 
nohup run_amos_threads $label Sworkload-rm 1400 27000 ${threads} &>> $pdir/out/${label}.log & 
wait $!

label=amosTxnUpdate_${suffix}
#nohup run_amos_threads $label Sworkload-ut 120 3100 ${threads} &>> $pdir/out/${label}.log & 
nohup run_amos_threads $label Sworkload-ut 120 4000 ${threads} &>> $pdir/out/${label}.log & 
wait $!


label=amosTxnRead_${suffix}
#nohup run_amos_threads $label Sworkload-rt 190 7600 ${threads} &>> $pdir/out/${label}.log & 
nohup run_amos_threads $label Sworkload-rt 1400 27000 ${threads} &>> $pdir/out/${label}.log & 
wait $!

label=amosSingletonUpdate_${suffix}
#nohup run_amos_threads $label Sworkload-us 480 5200 ${threads} &>> $pdir/out/${label}.log & 
nohup run_amos_threads $label Sworkload-us 530 6600 ${threads} &>> $pdir/out/${label}.log & 
wait $!

label=amosSingletonRead_${suffix}
#nohup run_amos_threads $label Sworkload-rs 1400 18500 ${threads} &>> $pdir/out/${label}.log & 
nohup run_amos_threads $label Sworkload-rs 2400 27000 ${threads} &>> $pdir/out/${label}.log & 
wait $!

