#!/bin/bash

#label=amosSingletonUpdate_rates1Ru3Rc; nohup run_amos_rate $label Sworkload-us 4800 5000 5100 5200  &>> $pdir/out/${label}.log &
label=amosSingletonUpdate_10Grates1Ru3Rc; nohup run_amos_rate $label Sworkload-us `seq 100 500 5000` 4800 5000 5100 5200  &>> $pdir/out/${label}.log &
wait $!
label=amosMixUpdate_10Grates1Ru3Rc; nohup run_amos_rate $label Sworkload-um `seq 100 400 3100` 3000 3100 3200 3300 &>> $pdir/out/${label}.log &
wait $!

label=amosTxnRead_10Grates1Ru3Rc; nohup run_amos_rate $label Sworkload-rt `seq 100 500 7600` 7400  &>> $pdir/out/${label}.log &
wait $!

label=amosSingletonRead_10Grates1Ru3Rc; nohup run_amos_rate $label Sworkload-rs `seq 100 1500 18500` 17500 18500  &>> $pdir/out/${label}.log &
wait $!

label=amosMixRead_10Grates1Ru3Rc; nohup run_amos_rate $label Sworkload-rm `seq 100 2000 12000` 12000   &>> $pdir/out/${label}.log &
wait $!

