#!/bin/awk -f 
function qsort(A, left, right,   i, last) {
	if (left >= right)
		return
	swap(A, left, left+int((right-left+1)*rand()))
	last = left
	for (i = left+1; i <= right; i++)
		if (A[i] < A[left])
			swap(A, ++last, i)
	swap(A, left, last)
	qsort(A, left, last-1)
	qsort(A, last+1, right)
}
function swap(A, i, j,   t) {
	t = A[i]; A[i] = A[j]; A[j] = t
}

function avg(A,i,j) {
	num = 0;
	sum = 0;
	for (n=i; n<=j; n++) {
		sum += A[n];
		num++;
	}
	return sum/num;
}

BEGIN {
	FS=",";
	n=1;
	warmup_time=30.0;
	
}

/Time/ {
	n_f=split($0,arr,",");
}

$0!~/Time/ {
	if ($1 > warmup_time) {
		for (i=1; i<=n_f; i++)  
			line[arr[i],n]=$i; 
		n++;
	}
} 

END {
	n-=2;
	for (j in arr) {
		for (i=1;i<=n;i++)  {
			#print arr[j],i " => " line[arr[j],i]; 
			array[i]=line[arr[j],i];
		}
		qsort(array,1,n-1);
		if (arr[j]=="Throughput")
               		res[arr[j]] = array[n-1];
        	else
               		res[arr[j]] = array[1];
		res[arr[j]] = avg(array, 1, n-1);
	}
	for (j=1; j<=n_f; j++) {
		print arr[j]" => "res[arr[j]]
	}
}
